### ISSUE TITLE
无法上传文档的问题

### ISSUE THREAD

**Issue by liuhqsir** [mnt-ltd/moredoc#1]
只要一点确定上传，服务就挂掉
![图片](https://user-images.githubusercontent.com/58692168/219600736-ce5fbfe9-d9ca-404e-8a72-9f1177987677.png)
试着打开过jieba文件没问题。

**Comment by TruthHun** [comment]
用最新发布的 v1.1 版本试下。之前的版本，用的结巴分词底层依赖于C，由于大家的操作系统不尽相同，不好排查缺少什么C库。1.1 版本，把结巴分词替换到了
