### ISSUE TITLE
登录验证码配置不生效

### ISSUE THREAD

**Issue by chanhungcheong** [mnt-ltd/moredoc#11]
v1.1.0版本，修改验证码长度时不生效，如图
![image](https://user-images.githubusercontent.com/90362750/225262327-c7d695f5-4dc0-453e-ad80-f9970080d211.png)
![image](https://user-images.githubusercontent.com/90362750/225262990-13099eef-4197-4554-9e81-14dac554017b.png)

**Comment by TruthHun** [comment]
收到，我这边跟进下

**Comment by TruthHun** [comment]
已在新发布的1.2.1版本中解决
