### ISSUE TITLE
文档页面需结构化数据优化

### ISSUE THREAD

**Issue by roberthailin** [mnt-ltd/moredoc#14]
可以根据搜索引擎的通用规则，将文档页面的数据结构好，好快速成为专业站及比其它站权重高，可参照360站点的结构化数据说明，其它搜索站点也一样，规则是通用的

**Comment by TruthHun** [comment]
前端是SPA单页应用，非SSR渲染的方式，无论怎么做页面数据结构都是不利于SEO的。

尽管是SPA的应用，但是目前演示站点 https://moredoc.mnt.ltd ，在百度和谷歌的收录看着也还可以。

做网站，没必要迎合搜索引擎，专注于内容就行。
