### ISSUE TITLE
 按照后端初始化命令：make api 报错

### ISSUE THREAD

**Issue by huaishitou** [mnt-ltd/moredoc#18]
按照后端初始化命令：make api
找不到文件 - *.proto
protoc --proto_path=. \
        --proto_path=./third_party \
        --proto_path=./api \
        --gogofaster_out="plugins=grpc,paths=source_relative:." \
        --grpc-gateway_out="paths=source_relative:." \

Missing input file.
make: *** [Makefile:22: api] Error 1

请问如何解决？

**Comment by TruthHun** [comment]
Windows 下，用 Git Bash，且在项目目录下执行 make api 操作。
