### ISSUE TITLE
转换失败的文档，能不能单独进行重转，而不是重转所有失败的文档

### ISSUE THREAD

**Issue by LianSchedule** [mnt-ltd/moredoc#22]
因为转换失败的文档较多，每次根据原因自己尝试排错后，希望能够马上进行验证，如果必须重转所有文档，需要花费的时间很长。

**Comment by TruthHun** [comment]
后台，文档列表编辑失败的文档，将文档状态变为`待转换`保存即可。

![image](https://github.com/mnt-ltd/moredoc/assets/9262441/7c5d4430-00b4-4b0e-aee9-d660601065a8)
