### ISSUE TITLE
反代后，下载链接的域名仍然是源站

### ISSUE THREAD

**Issue by LianSchedule** [mnt-ltd/moredoc#23]
比如源站域名A.com，在另一台服务器上部署B.com，反代到A.com。
访问B.com时，svg预览图的链接域名是B.com，符合预期。
但是访问B.com，下载文档时，实际的下载链接的域名是A.com，失去了反代的意义。
请问该怎么解决这个问题？

**Comment by TruthHun** [comment]
下载地址是根据你后台配置的这个域名拼接的。

![image](https://github.com/mnt-ltd/moredoc/assets/9262441/2fffe779-de75-44b9-968f-d23c2a6b9a19)

**Comment by LianSchedule** [comment]
这样看起来没法解决这个问题，请问有其他办法解决这个问题吗？
