### ISSUE TITLE
验证码刷新不及时

### ISSUE THREAD

**Issue by LianSchedule** [mnt-ltd/moredoc#24]
第1种复现步骤：
（1）第一次进入页面，输入正确的账号密码，但是不要输入正确的验证码
（2）点击登录，此时提示“验证码错误”
（3）此时输入正确的验证码，点击登录，仍然会提示“验证码错误”
第2种复现步骤：
（1）第一次进入页面，输入错误的账号密码，输入正确的验证码
（2）点击登录，此时提示“用户名或者密码错误”
（3）此时输入正确的账号密码，点击登录，仍然会提示“验证码错误”

有的用户在这里不知道点击验证码图片获取新的验证码，所以就卡在这里了

**Comment by TruthHun** [comment]
将在发布的 2.0 版本中修复该问题
