### ISSUE TITLE
违规文档如何禁止上传？

### ISSUE THREAD

**Issue by LianSchedule** [mnt-ltd/moredoc#27]
违规的文档，网站不可以保留，必须删除，回收站中也要删除，可是这样的话，如果多个用户先后上传这个文档，那么网站管理员就需要多次进行审查，比较浪费时间。

**Comment by TruthHun** [comment]
在管理后台->文档管理->文档列表，找到对应的文档，编辑这个文档，选择状态为`已禁用`，这时非管理员就没法再前台查看到了。目前暂时没有更好的办法处理违规文档，建议只允许特定的人上传文档。
