### ISSUE TITLE
修改文档信息的一个bug

### ISSUE THREAD

**Issue by LianSchedule** [mnt-ltd/moredoc#28]
上传文档后，在“个人中心”“我的文档”里面搜关键词，然后编辑这个文档，此时文件名和描述里会出现多余的mark文字，修改过一次文件名后，再次提交时，会报错，看起来是文档评分被多余地除以了100，形成了小数，导致提交失败。

**Comment by TruthHun** [comment]
这个bug已在 v3.2 的版本中修复，感谢反馈
