### ISSUE TITLE
建议增加一个请求头，用以标识该请求是否允许被缓存

### ISSUE THREAD

**Issue by LianSchedule** [mnt-ltd/moredoc#32]
用于nginx代理缓存，但是目前无法区分哪些请求可以被缓存，哪些请求不可以被缓存，建议在不允许被缓存的请求中新增一个自定义的请求头，比如登录接口，不允许被缓存，否则任何用户进行登录都将得到被缓存的用户的登录信息。
![image](https://github.com/mnt-ltd/moredoc/assets/29496245/a84e5307-0f27-4ef5-8b85-f6c5874360b4)

**Comment by TruthHun** [comment]
不需要设置任何缓存，nginx配置也不需要设置任何缓存，程序会自动设置判断哪些需要缓存。如果你这边非要设置缓存的话，那么凡是 `/api` 开头的请求都不要设置缓存。
