### ISSUE TITLE
新版本发布时，可否给出详细的功能变化清单

### ISSUE THREAD

**Issue by LianSchedule** [mnt-ltd/moredoc#34]
由于看不到pro版的代码变化，我们只能通过作者的描述来了解功能变化。
除了大的功能变化，我们对于小的功能变化，比如新增了积分和人民币的换算也比较敏感，希望作者可以给出详细的清单。

**Comment by TruthHun** [comment]
积分与人民币的换算，在早期增加积分功能的时候就已经有了，没法在积分功能清单中列出更小粒度的变化。就好比说增加了微信支付功能，然后功能清单中列出：配置微信支付client_id、配置微信支付密钥、配置微信支付回调地址等是不怎么合理的。

当然，我们在发新版本，也是尽可能把有必要的功能清单说清楚的。就好比当前 v3.2 的版本：https://www.bookstack.cn/read/moredoc/2.2.0.md 。 在这个版本中增加了激励广告功能，相关配置都有说明。
