### ISSUE TITLE
部分接口存在未授权访问问题

### ISSUE THREAD

**Issue by lengyf** [mnt-ltd/moredoc#38]
版本号：2.4.0
问题描述：
在不登录的情况下访问/api/v1/user/list接口，能够获取用户列表数据。
在不登录的情况下访问/api/v1/stats接口，能够获取服务器及应用版本等敏感数据。
在不登录的情况下访问/api/v1/device接口，能够获取服务器信息等敏感数据。

**Comment by TruthHun** [comment]
感谢反馈。其中`/api/v1/user/list`是可以访问用户非隐私的公开数据的，只有管理员访问这个接口时才会获取到更详实的数据。另外两个API接口，敏感数据我们这边处理下，只有管理员才能获取相应数据。
