### ISSUE TITLE
首页分类列表名称的文字较长时，显示不是很好

### ISSUE THREAD

**Issue by LianSchedule** [mnt-ltd/moredoc#41]
![微信截图_20240507214437](https://github.com/mnt-ltd/moredoc/assets/29496245/623dddf9-9b39-4a22-ac95-e7d492407964)
如右侧所见，名称较长时，将占用两行空间，并且可以看见第三行内容的顶部的一部分。

**Comment by TruthHun** [comment]
3.1 版本已修复和发布。Chrome浏览器的兼容问题。Windows的Chrome浏览器必现，Mac下的Chrome复现不了这种场景。
