### ISSUE TITLE
请强化全文搜索功能

### ISSUE THREAD

**Issue by bluezealot** [mnt-ltd/moredoc#6]
目前的搜索功能是基于摘要内容创建的索引，其实我理解这个系统具备全文文字创建索引的能力，所以搜索用索引能否基于全文创建？

**Comment by TruthHun** [comment]
开源的社区版，没有全文搜索功能，只是简单通过MySQL 的Like 查询简单查询标题和摘要实现。

普惠版里面有全文搜索功能，索引文档标题和文档文本内容。

**Comment by bluezealot** [comment]
原来如此，谢谢。
