### ISSUE TITLE
jbig2dec error: incompatible jbig2dec header(0.17) and library (0.18) versions (segment -1)

### ISSUE THREAD

**Issue by SakuranaRanbom** [mnt-ltd/moredoc#8]
![image](https://user-images.githubusercontent.com/48652800/222312324-2724719a-370d-48a6-bcd9-6edf93e8d2bd.png)

ubuntu 20

上传大于50m 文档时，会转换失败

**Comment by TruthHun** [comment]
建议mupdf升级到最新版试下。好像老版本有这个问题。详见：https://bbs.archlinux.org/viewtopic.php?id=250030

**Comment by TruthHun** [comment]
mupdf 下载地址：https://mupdf.com/releases/index.html

**Comment by TruthHun** [comment]
你好，请问问题解决了没

**Comment by SakuranaRanbom** [comment]
> 你好，请问问题解决了没

暂时还没有。官方下载的make后
![image](https://user-images.githubusercontent.com/48652800/223051606-20601eb9-8723-46b3-839f-552c3b12f3d5.png)

应该是glibc版本问题，要求glibc 2.35，ubuntu20是2.31，支持的mupdf最高版本是1.16.1。

暂时还没办法验证
