### ISSUE TITLE
部分文档转换失败，无法预览

### ISSUE THREAD

**Issue by chanhungcheong** [mnt-ltd/moredoc#9]
上传的是epub电子书，如下图：
![image](https://user-images.githubusercontent.com/90362750/223662340-91d5053a-b9c7-4f73-9fa0-ac2befcc9408.png)
![image](https://user-images.githubusercontent.com/90362750/223662913-70d0e181-00a0-4108-93ea-d718f258c177.png)
上传pptx格式文档，也转换失败，如下图：
![image](https://user-images.githubusercontent.com/90362750/223663118-d7d70d63-1d91-443c-8052-e4211b008cd0.png)
![image](https://user-images.githubusercontent.com/90362750/223663194-d0a22dbd-cd0e-4932-868c-1273fb87b963.png)
doc和pdf都可以正常预览。请问这可以怎样处理？从哪里可以看到报错日志？

**Comment by TruthHun** [comment]
把你这边转换失败的文档上传到演示站点看下，如果演示站点能正常转换而你的不能正常转换，请排查和确认程序环境以配置正确。

**Comment by chanhungcheong** [comment]
找到原因了，是home目录的问题，感谢
